test

diff --git a/.github/workflows/compatibility-test.yml b/.github/workflows/compatibility-test.yml
--- a/.github/workflows/compatibility-test.yml
+++ b/.github/workflows/compatibility-test.yml
@@ -22,7 +22,13 @@ jobs:
       - name: Get Connection Info
         run: |
           # delete cluster if exists
-          ticloud cluster list 1372813089206721319 -o json > cluster
+          result=$(echo `ticloud cluster list 1372813089206721319 -o json`)
+          if [[ $result == "Error:"* ]]; then
+            echo "list cluster failed"
+            exit 1
+          fi
+          echo $result > cluster
+          
           total=$(jq '.total' cluster);
           for i in $(seq 1 $total);
           do
@@ -32,7 +38,13 @@ jobs:
 
           # create cluster
           ticloud cluster create --project-id 1372813089206721319 --cluster-name tls-test --cloud-provider AWS -r us-east-1 --root-password ${{ secrets.TIDB_CLOUD_PASSWORD }} --cluster-type SERVERLESS;
-          ticloud cluster list 1372813089206721319 -o json > cluster
+          result=$(echo `ticloud cluster list 1372813089206721319 -o json`)
+          if [[ $result == "Error:"* ]]; then
+            echo "list cluster failed"
+            exit 1
+          fi
+          echo $result > cluster
+          
           cat cluster
           echo "TIDB_CLOUD_USER=$(jq '.items[0].status.connection_strings.default_user' cluster)" >> $GITHUB_ENV
           echo "TIDB_CLOUD_HOST=$(jq '.items[0].status.connection_strings.standard.host' cluster)" >> $GITHUB_ENV
diff --git a/.github/workflows/create-test.yml b/.github/workflows/create-test.yml
--- a/.github/workflows/create-test.yml
+++ b/.github/workflows/create-test.yml
@@ -1,9 +1,8 @@
 name: Serverless Create Test1
 
 on:
-  pull_request:
-#  schedule:
-#    - cron: "0/30 * * * *"  # every 30 minutes
+  schedule:
+    - cron: "0/30 * * * *"  # every 30 minutes
   workflow_dispatch:
 
 jobs:
@@ -23,7 +22,13 @@ jobs:
       - name: Delete all serverless
         run: |
           # delete all serverless
-          ticloud cluster list 1372813089447741295 -o json > cluster
+          result=$(echo `ticloud cluster list 1372813089447741295 -o json`)
+          if [[ $result == "Error:"* ]]; then
+            echo "list cluster failed"
+            exit 1
+          fi
+          
+          echo $result > cluster
           total=$(jq '.total' cluster);
           for i in $(seq 1 $total);
           do
@@ -35,7 +40,7 @@ jobs:
     needs: setup
     strategy:
       matrix:
-        region: [us-east-1] #[ us-east-1, us-west-2, ap-northeast-1, ap-southeast-1, eu-central-1 ]
+        region: [ us-east-1, us-west-2, ap-northeast-1, ap-southeast-1, eu-central-1 ]
     runs-on: ubuntu-latest
     timeout-minutes: 10
     steps:
